# FastText with residue-level tokenization
task: fluorescence

embedder:
  type: fasttext
  model_path: models/fluorescence_fasttext_residue.bin
  tokenization: residue  # Individual amino acids as tokens
  dim: 128
  pos_encoder: sinusoid
  fusion: add
  train_params:
    epochs: 10
    window: 5
    min_count: 1
    sg: 1

predictor:
  type: linear  # Using linear model for variety
  alpha: 1.0
  seed: 42

data:
  train_size: 0.5
  val_split: 0.1
  max_length: 500
  seed: 42

output_dir: results/residue