# FastText baseline configuration
task: fluorescence

embedder:
  type: fasttext
  model_path: models/fluorescence_fasttext_kmer.bin
  tokenization: kmer
  k: 6
  dim: 128
  train_params:
    epochs: 10
    window: 5
    min_count: 1
    sg: 1  # Skip-gram

predictor:
  type: rf
  n_estimators: 100
  max_depth: 20
  seed: 42

data:
  train_size: 0.5
  val_split: 0.1
  max_length: 500
  seed: 42

output_dir: results/baseline