data:
  max_length: 200
  seed: 42
  train_size: 0.1
  val_split: 0.2
embedder:
  dim: 32
  fusion: add
  model_path: models/fluorescence_fasttext_residue.bin
  pos_encoder: sinusoid
  tokenization: residue
  train_params:
    epochs: 2
    min_count: 1
    sg: 1
    window: 3
  type: fasttext
output_dir: results/residue
predictor:
  max_depth: 5
  n_estimators: 10
  seed: 42
  type: rf
task: fluorescence
