# Test pre-trained model with tiny config
task: fluorescence

embedder:
  type: fasttext
  model_path: models/test_pretrained_finetuned.bin
  pretrained_path: models/mock_uniref50_pretrained.bin
  fine_tune: true
  tokenization: kmer
  k: 6
  dim: 128  # Must match pre-trained model
  train_params:
    epochs: 2
    window: 5
    min_count: 1
    sg: 1

predictor:
  type: rf
  n_estimators: 10
  max_depth: 5
  seed: 42

data:
  train_size: 0.1
  val_split: 0.2
  max_length: 200
  seed: 42

output_dir: results/test_pretrained